### PR TITLE
Fixed grammar

### PR DESCRIPTION
**Pull request by benji-lewis**

### CODE REVIEW

**Review by thebeanogamer — APPROVED** [review]
There are a couple of lower-case `3d`s that you've missed, but a large improvement. I'm not sure why you've changed to the CC license though?

**Comment by thebeanogamer** [comment]
No I don't know why it emailed me and asked for a review either.

**Comment by thebeanogamer** [comment]
WHY DO I HAVE COMMIT TO MASTER PERMISSIONS?

**Comment by benji-lewis** [comment]
I just removed a license in order to consolidate it

**Comment by thebeanogamer** [comment]
From memory, the CC license was from the template, the MIT one was from back when the repo was Oli's nightmarish original site

**Comment by thebeanogamer** [comment]
I would find it in the commit history, but then I clicked on commits and ran away in fear

**Pull request closed without merging**
